username = "testuser"
password = "testPW"
baseurl = "http://localhost:8000"
urlget = ""
urlput = "/users"
checkmode = true
entries = 2
filter1 = "."
filter2 = "."
listof = "AAccount"
attr = "Process Instance.Task Information.Target User"