username = "testuser"
password = "testPW"
baseurl = "http://localhost:8000"
urlget = "/"
urlput = "/users"
urlfilter =  [[ "aa::bb::cc", "AA" ]]
printmode = false
checkmode = false
filemode = true
entries = 5
filter1 = "AAccount"
filter2 = "Update"
listof = "AAccount"
attr = "Process Instance.Task Information.Target User"