username = "testuser"
password = "testPW"
baseurl = "http://localhost:8000"
urlget = ""
urlput = "/users"
printmode = true
checkmode = false
filemode = true
entries = 1
filter1 = "AAccount"
filter2 = "Update"
listof = "AAccount"
attr = "Process Instance.Task Information.Target User"