username = "testuser"
password = "testPW"
baseurl = "http://localhost:8000"
urlget = "/te?q=123+eq+123 AND "
urlput = "/users"
urlfilter =  [[ "aa::bb::cc", ["AA", "BB"]], [ "ggggg", ["aa","bb","cc" ] ]]
#urlfilter =  [[ "aa::bb::cc", ["AA","BB","CC" ]], [ "ggggg", ["aa","bb","cc" ] ]]
printmode = true
checkmode = false
filemode = false
entries = 5
filter1 = "AAccount"
filter2 = "Update"
listof = "AAccount"
attr = "Process Instance.Task Information.Target User"

