syntax = "proto3";
import "google/protobuf/timestamp.proto";
package requestsautomation;



service User {
  rpc ConfReload(UserRequest) returns (ConfigResponse);
  rpc CheckCon(UserRequest) returns (ConfigResponse);
  rpc GenList(FilterRequest) returns (ListResponse);
  rpc DbDelete(UserRequest) returns (UserResponse);
  rpc ProvTasksList(FilterRequest) returns (ListResponse);
  rpc ProvAction(ProvAcionRequest) returns (Dictionary);
}
enum ActionType
{   // whatever contents...
    retry = 0;
    bar = 1;
}

message FilterRequest {
  map<string, FilterValues> urlfilter = 1;
  string urlget = 2;
  int32 limit = 3;
  string mode = 4;
}

message FilterValues {
  repeated string values = 1;
}


message UserRequest {
  string id = 1;
}

message Task {
  string id = 1;
  string status = 2;
}

message Dictionary {
  map<string, Task> pairs = 1;
}

message ProvAcionRequest {  ActionType action  = 1;}

message TaskDetails {
  string key = 1;
  string object_name = 2;
  string task_name = 3;
  string target_user = 4;
  string creation_date = 5;
}

message ListResponse {  
  google.protobuf.Timestamp time = 1;
  int32  result = 2;
  string message = 3;
  repeated TaskDetails tasks = 4;
}

message UserResponse { int64 result = 1; }

message ConfigResponse { string result = 1; }

/* service Admin {
  rpc GetRequestCount(GetCountRequest) returns (CounterResponse);
} */

/* message GetCountRequest {}

message CounterResponse { uint64 count = 1; } */
